apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: pyflink-hello-world
spec:
  image: golebtom/pyflink-hello-world:v0.26
#  image: golebtom/pyflink-conda:v0.2
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/opt/flink-python-1.18.0.jar # Note, this jarURI is actually a placeholder
    entryClass: "org.apache.flink.client.python.PythonDriver"
    args: ["-pyclientexec", "/opt/conda/envs/pyflink/bin/python3", "-py", "/opt/flink/usrlib/pyflink_hello_world.py"]
    parallelism: 2
    upgradeMode: stateless
